#!/usr/bin/env bash

install() {
  link "$REPOSITORY_ROOT" ~/.config/nvim
  mkdir -p "$REPOSITORY_ROOT/autoload"
  curl --insecure -fLso "$REPOSITORY_ROOT/autoload/plug.vim" \
    https://raw.github.com/junegunn/vim-plug/master/plug.vim
}

source <(curl -Lfs https://git.io/lnkr)
